name: Deploy FastAPI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Latest Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Pull Latest Code
        run: |
          cd /home/ubuntu/HNG/fastapi-book-project
          git reset --hard origin/main  # Ensures full sync with GitHub
          git pull origin main

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          cd /home/ubuntu/HNG/fastapi-book-project
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Restart FastAPI Service
        run: |
          sudo systemctl restart fastapi
